name: Technically Competent
url: http://technicallycompetent.com
description: Stuff Mark Does

permalink: /:title/
paginate: 30
paginate_path: "page/:num"

excerpt_separator: "<!--excerpt-->"

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', '.git']
