name: Technically Competent
url: http://technicallycompetent.com
description: Stuff Mark Does

permalink: /:title/
paginate: 10
paginate_path: "blog/page:num"

excerpt_separator: "<!--excerpt-->"

plugins: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
